@Library('platform') _
import net.atos.Globals

pipeline {
    environment {
        def APP_NAME = "sample" // Your Git application name For e.g. sample
        def GIT_REPO_NAME = "SamsaliFathima" // Your Git repository name, For e.g. mrganeshkudale
        def DEPLOY_ENV = "dev" // Keep this value as default, For e.g. dev
        def GIT_PAT = "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" // Your Git PAT, For e.g. gph_sdfenndsdu545ffsd9dfsdf45dfs_d
        def NAMESPACE = "${BUILD_USER}" // Keep this value as default, For e.g. sample
    }
    agent any
    stages {
        stage('Code Checkout') {
            steps {
                sh "if [ -d ${APP_NAME} ]; then rm -rf ${APP_NAME}; fi"
                sh "git clone https://${GIT_PAT}@github.com/${GIT_REPO_NAME}/${APP_NAME}.git"
            }
        }
        stage('Azure Cloud Connect'){
            steps {
                  azure_connect()
            }
        }
        stage('Build & Image'){
            steps {
                sh "cd ${APP_NAME} && az acr build -r tntaksreg -t ${APP_NAME} ."
            }
        }
        stage('Deploy'){
            steps {
                //clean_deployments("${APP_NAME}","${DEPLOY_ENV}")
                create_deployments("${APP_NAME}","${DEPLOY_ENV}")
            }
        }
    }
    post {
        success {
            echo "Your application is online now."
        }
        failure {
            echo "Please check logs for more details!"
        }
    }
}
